# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from google.cloud.spanner_admin_instance_v1 import GetInstanceRequest, Instance

class InstanceAdminServicer(object):
    """Cloud Spanner Instance Admin API
    """

    def GetInstance(self, request, context):
        """Gets information about an instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

def add_InstanceAdminServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetInstance': grpc.unary_unary_rpc_method_handler(
            servicer.GetInstance,
            request_deserializer=GetInstanceRequest.deserialize,
            response_serializer=Instance.serialize,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'google.spanner.admin.instance.v1.InstanceAdmin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
